### PR TITLE
Climatization

### PR DESCRIPTION
**Pull request by nikagl**
Add post request and call to turn on pre-climatization (can be disabled by commenting it out :), no features yet for command line)

### CODE REVIEW

**Comment by molobrakos** [comment]
Thanks for sharing this, the feature is now implemented, please test if it works for you!

**Comment by nikagl** [comment]
Not yet, I get following error:
`ERROR:volvooncall:Failure when communcating with the server: 500 Server Error: Internal Server Error for url: https://vocapi.wirelesscar.net/customerapi/rest/v3.0/vehicles/...`

Will test in more detail tomorrow (battery is empty)...

**Comment by nikagl** [comment]
The post call needs to be different:
`            if post:
                method = self._session.post
                res = method(url, "{}")
            else:
                method = self._session.get
                res = method(url, timeout=TIMEOUT.seconds)`

**Comment by nikagl** [comment]
`"{}"` instead of `timeout=TIMEOUT.seconds`

**Comment by nikagl** [comment]
and `is_preclimatization_on` needs to be `is_heater_on` in voc.py.

Last but not least, checking preclimatization needs to be done using heater parameters:
```u'heater': {u'seatSelection': {u'frontDriverSide': True,
                               u'frontPassengerSide': True,
                               u'rearDriverSide': False,
                               u'rearMid': False,
                               u'rearPassengerSide': False},
            u'status': u'onOther',
            u'timer1': {u'state': False, u'time': u'08:05'},
            u'timer2': {u'state': False, u'time': u'17:00'},
            u'timestamp': u'2017-01-03T16:04:13+0000'},```

The heater.status = onOther is what is returned in my case when preclimatization is on...

Here's a list of all what is returned. Note that I XXXX-ed out some stuff, if I forgot something, please treat confidentially ;)

``` u'assistanceCallSupported': True,
 u'averageFuelConsumption': 45.0,
 u'averageFuelConsumptionTimestamp': u'2017-01-03T07:44:58+0000',
 u'averageSpeed': 62,
 u'averageSpeedTimestamp': u'2017-01-03T07:44:58+0000',
 u'bCallAssistanceNumber': u'+XXXXXX',
 u'brakeFluid': u'Normal',
 u'brakeFluidTimestamp': u'2017-01-03T07:44:58+0000',
 u'bulbFailures': [],
 u'bulbFailuresTimestamp': u'2017-01-03T07:44:58+0000',
 u'calculatedPosition': {u'heading': None,
                         u'latitude': None,
                         u'longitude': None,
                         u'speed': None,
                         u'timestamp': None},
 u'carLocatorDistance': 1000,
 u'carLocatorSupported': True,
 u'carLocked': True,
 u'carLockedTimestamp': u'2017-01-03T07:44:58+0000',
 u'climatizationCalendarMaxTimers': 8,
 u'climatizationCalendarVersionsSupported': [],
 u'connectionStatus': u'ConnectedWithPower',
 u'connectionStatusTimestamp': u'2017-01-03T15:47:16+0000',
 u'country': {u'iso2': u'NL'},
 u'customerServiceId': u'XXXXXX',
 u'distanceToEmpty': 350,
 u'distanceToEmptyTimestamp': u'2017-01-03T07:44:58+0000',
 u'doors': {u'frontLeftDoorOpen': False,
            u'frontRightDoorOpen': False,
            u'hoodOpen': False,
            u'rearLeftDoorOpen': False,
            u'rearRightDoorOpen': False,
            u'tailgateOpen': False,
            u'timestamp': u'2017-01-03T07:44:58+0000'},
 u'engineCode': u'XXXXXX',
 u'engineRunning': False,
 u'engineRunningTimestamp': u'2017-01-03T07:44:58+0000',
 u'engineStartSupported': False,
 u'exteriorCode': u'XXXXXX',
 u'fuelAmount': 26,
 u'fuelAmountLevel': 57,
 u'fuelAmountLevelTimestamp': u'2017-01-03T07:44:58+0000',
 u'fuelAmountTimestamp': u'2017-01-03T07:44:58+0000',
 u'fuelTankVolume': 45,
 u'fuelType': u'HEV',
 u'gearboxCode': u'XXXXXX',
 u'grossWeight': 2505,
 u'heater': {u'seatSelection': {u'frontDriverSide': True,
                                u'frontPassengerSide': True,
                                u'rearDriverSide': False,
                                u'rearMid': False,
                                u'rearPassengerSide': False},
             u'status': u'onOther',
             u'timer1': {u'state': False, u'time': u'08:05'},
             u'timer2': {u'state': False, u'time': u'17:00'},
             u'timestamp': u'2017-01-03T16:04:13+0000'},
 u'highVoltageBatterySupported': True,
 u'honkAndBlinkDistance': 500,
 u'honkAndBlinkSupported': True,
 u'honkAndBlinkVersionsSupported': [u'honkAndOrBlink', u'honkAndBlink'],
 u'hvBattery': {u'distanceToHVBatteryEmpty': 50,
                u'distanceToHVBatteryEmptyTimestamp': u'2017-01-03T15:47:16+0000',
                u'hvBatteryChargeModeStatus': u'Allowed',
                u'hvBatteryChargeModeStatusTimestamp': u'2017-01-03T15:47:16+0000',
                u'hvBatteryChargeStatus': u'PlugInserted',
                u'hvBatteryChargeStatusDerived': u'CablePluggedInCar_FullyCharged',
                u'hvBatteryChargeStatusDerivedTimestamp': u'2017-01-03T15:47:16+0000',
                u'hvBatteryChargeStatusTimestamp': u'2017-01-03T15:47:16+0000',
                u'hvBatteryChargeWarning': u'UnexpectedPowerloss',
                u'hvBatteryChargeWarningTimestamp': u'2016-12-31T12:34:00+0000',
                u'hvBatteryLevel': 100,
                u'hvBatteryLevelTimestamp': u'2017-01-03T15:47:16+0000',
                u'timeToHVBatteryFullyCharged': 0,
                u'timeToHVBatteryFullyChargedTimestamp': u'2017-01-03T15:47:16+0000'},
 u'interiorCode': u'XXXXXX',
 u'journalLogEnabled': True,
 u'journalLogSupported': True,
 u'lockSupported': True,
 u'maxActiveDelayChargingLocations': 7,
 u'modelYear': 2016,
 u'numberOfDoors': 5,
 u'odometer': 36298040,
 u'odometerTimestamp': u'2017-01-03T07:44:58+0000',
 u'overrideDelayChargingSupported': True,
 u'parkedIndoor': False,
 u'parkedIndoorTimestamp': u'2017-01-03T16:04:13+0000',
 u'position': {u'heading': None,
               u'latitude': 52.079185485839844,
               u'longitude': 4.3350982666015625,
               u'speed': None,
               u'timestamp': u'2017-01-03T07:43:29+0000'},
 u'preclimatizationSupported': True,
 u'registrationNumber': u'HT961F',
 u'remoteClimatizationStatus': u'Climatization',
 u'remoteClimatizationStatusTimestamp': u'2017-01-03T15:47:16+0000',
 u'remoteHeaterSupported': False,
 u'sendPOIToVehicleVersionsSupported': [u'sendSinglePOIToVehicle'],
 u'serverVersion': u'${project.version}-${project.artifactId}',
 u'service': u'https://vocapi.wirelesscar.net/customerapi/rest/v3.0/vehicles/XXXXXX/services/XXXXXX',
 u'serviceType': u'RVPC',
 u'serviceWarningStatus': u'Normal',
 u'serviceWarningStatusTimestamp': u'2017-01-03T07:44:58+0000',
 u'startTime': u'2017-01-03T16:09:22+0000',
 u'status': u'Started',
 u'status.parkedIndoor.supported': True,
 u'statusTimestamp': u'2017-01-03T16:09:22+0000',
 u'subscriptionEndDate': u'2018-12-24T12:00:00+0000',
 u'subscriptionStartDate': u'2015-12-24T12:00:00+0000',
 u'subscriptionType': u'PREMIUM_2013',
 u'timeFullyAccessible': 7200,
 u'timeFullyAccessibleUntil': u'2017-01-08T07:43:28+0000',
 u'timePartiallyAccessible': 31680,
 u'timePartiallyAccessibleUntil': u'2017-01-25T07:43:28+0000',
 u'tripMeter1': 6285500,
 u'tripMeter1Timestamp': u'2017-01-03T07:44:58+0000',
 u'tripMeter2': 6285500,
 u'tripMeter2Timestamp': u'2017-01-03T07:44:58+0000',
 u'tyreDimensionCode': u'3521R517',
 u'tyreInflationPressureHeavyCode': u'3521YX0E',
 u'tyreInflationPressureLightCode': u'3521YT0P',
 u'tyrePressure': {u'frontLeftTyrePressure': u'Normal',
                   u'frontRightTyrePressure': u'Normal',
                   u'rearLeftTyrePressure': u'Normal',
                   u'rearRightTyrePressure': u'Normal',
                   u'timestamp': u'2017-01-03T07:44:58+0000'},
 u'unlockSupported': True,
 u'unlockTimeFrame': 120,
 u'vehicleId': u'XXXXXX',
 u'vehiclePlatform': u'3521',
 u'vehicleType': u'V60',
 u'vehicleTypeCode': u'XXXXXX',
 u'verificationTimeFrame': 120,
 u'vin': u'XXXXXX',
 u'washerFluidLevel': u'Low',
 u'washerFluidLevelTimestamp': u'2017-01-03T07:44:58+0000',
 u'windows': {u'frontLeftWindowOpen': False,
              u'frontRightWindowOpen': False,
              u'rearLeftWindowOpen': False,
              u'rearRightWindowOpen': False,
              u'timestamp': u'2017-01-03T07:44:58+0000'}}]
              ```

**Comment by nikagl** [comment]
This seems to work:
```
        return ((self.remoteHeaterSupported or self.preclimatizationSupported) and
                 self.heater['status'] != 'off')
```

**Comment by molobrakos** [comment]
Thanks fixed according to your last comment. Does the post call still have to change as well?

**Comment by nikagl** [comment]
Yeah, the other one is only for the status command. Wanted to issue a pull request, but guess I don't have to anymore ;)

**Comment by molobrakos** [comment]
The "{}" looks strange, also it works fine for me.
What happend if you change it into post(url, {}) instead post(url, "{}")

**Comment by nikagl** [comment]
I took {} from the traces I made while using the app. Off course you can use single quotes too, but without the quotes it won't work... It generates:
'''
ERROR:volvooncall:Failure when communicating with the server: 500 Server Error: Internal Server Error for url: https://vocapi.wirelesscar.net/customerapi/re....
'''

**Comment by nikagl** [comment]
Also when using Postman (for testing) the body needs to contain {}... without it, it generates an error:
```
{
  "errorLabel": "ServiceUnableToStart",
  "errorDescription": "The service was unable to start"
}
```

**Comment by molobrakos** [comment]
ok, I see. Updated now.

**Comment by nikagl** [comment]
Almost:

and `is_preclimatization_on` needs to be `is_heater_on` in voc.py.

Otherwise it generates error:

```
X:\Python27\volvooncall-master>python voc status
XXXXXX (V60/2016) XXXXXX 36356km (fuel 53% 390km)
    position: 52.04741668701172,5.09767913818359
    locked: yes
Traceback (most recent call last):
  File "voc", line 119, in <module>
    main()
  File "voc", line 104, in main
    print_vehicle(vehicle, args['-g'])
  File "voc", line 62, in print_vehicle
    print('    preclimatization: %s' % ('on' if vehicle.is_preclimatization_on else 'off'))
AttributeError: 'Vehicle' object has no attribute 'is_preclimatization_on'
```

**Comment by molobrakos** [comment]
ah, of course. fixed.

**Pull request closed without merging**
