### PR TITLE
Support for USA units of measure in dashboard

### PR DESCRIPTION
**Pull request by y34hbuddy**
Added conversions in dashboard/HA integration for:

- km to mile
- km/h to mph
- L to US gal
- L/100km to mpg
- "tyre" to "tire" :)

### CODE REVIEW

**Comment by y34hbuddy** [comment]
Hi @decompil3d yes, I tested end-to-end with Home Assistant using standard metric units, Scandinavian units, and US units. Thx for the review!

**Comment by y34hbuddy** [comment]
FWIW - here are screenshots of my HA dashboard with (1) default, (2) Scandinavian, and (3) US units configured:

Volvo_Scandinavian
Volvo_US
Volvo_Default
.

**Comment by decompil3d** [comment]
Looks great. I can merge but probably won't have time on my laptop to publish to pypi until Monday.

**Comment by y34hbuddy** [comment]
Looks like an issue with `docutils` in Python 3.9:

```
  File "/home/runner/work/volvooncall/volvooncall/.tox/lint/lib/python3.9/site-packages/docutils/statemachine.py", line 1506, in string2lines
    astring = whitespace.sub(' ', astring)
TypeError: expected string or bytes-like object
```

**Comment by y34hbuddy** [comment]
@decompil3d this still doesn't pass linter in Python 3.9, but I did fix a linter error introduced in a different PR (https://github.com/molobrakos/volvooncall/pull/87).

Not sure how else to get this to pass for Python 3.9 as the only culprit in volvooncall code is calling `setuptools.setup()`.

Will keep hacking away at it...

**Comment by y34hbuddy** [comment]
@decompil3d not sure if this is ideal (I'm not an expert on tox or setuptools), but the latest commit seems to fix all inter errors in my local machine.

**Comment by decompil3d** [comment]
There don't seem to be any rst files here, so your fix is likely fine. I'll try to merge and publish on Monday when I'm in front of my computer.

**Comment by y34hbuddy** [comment]
Thanks so much, @decompil3d, and thanks for letting me contribute!

**Comment by decompil3d** [comment]
Released in 0.10.1

**Comment by Gollam** [comment]
@decompil3d this introduced a new bug, "Time to fully charged" is now also converted to USA units, because the unit of that field is "minutes", and this code applies the multiplier:

`elif val and "mi" in self.unit:
     return round(val * 0.621371, 1)`

**Comment by y34hbuddy** [comment]
Good catch @Gollam -- my Volvo isn't hybrid/electric so I wouldn't have caught this. Will submit a fix shortly.

**Pull request merged**
